services:
  api:
    build: ./api
    environment:
      NODE_ENV: production
      PORT: 3000
      GCS_BUCKET: trakto-videos-469221
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_sa.json
      GCS_SIGNED_URL_EXPIRES: 3600
    volumes:
      - ./secrets:/run/secrets:ro
    expose:
      - "3000"
    # opcional para debugar diretamente
    ports:
      - "3000:3000"

  web:
    build: ./web
    depends_on:
      - api
    ports:
      - "8080:80"
